const {
  REACT_APP_API_BASE_URL,
  REACT_APP_API_LOGIN_V2,
  REACT_APP_API_LOGIN_ENDPOINT,
  REACT_APP_API_REGISTER_V1,
  REACT_APP_API_REGISTER_ENDPOINT,
  REACT_APP_API_PETS_V1,
  REACT_APP_API_PETS_V2,
  REACT_APP_API_PETS_ENDPOINT,
  REACT_APP_API_SAVED_PETS_V1,
  REACT_APP_API_SAVED_PETS_ENDPOINT,
  REACT_APP_API_VERIFY_TOKEN_V1,
  REACT_APP_API_VERIFY_TOKEN,
} = process.env;

export {
  REACT_APP_API_BASE_URL,
  REACT_APP_API_LOGIN_V2,
  REACT_APP_API_LOGIN_ENDPOINT,
  REACT_APP_API_REGISTER_V1,
  REACT_APP_API_REGISTER_ENDPOINT,
  REACT_APP_API_PETS_V1,
  REACT_APP_API_PETS_V2,
  REACT_APP_API_PETS_ENDPOINT,
  REACT_APP_API_SAVED_PETS_V1,
  REACT_APP_API_SAVED_PETS_ENDPOINT,
  REACT_APP_API_VERIFY_TOKEN_V1,
  REACT_APP_API_VERIFY_TOKEN,
};
